### ISSUE TITLE
code not work

### ISSUE THREAD

**Issue by umesh-21** [ShimingWang98/Facial_Feature_Crafting_against_Inversion_based_Identity_Theft#1]
I would like to bring to your attention some discrepancies between the README file and the actual code in the repository, specifically regarding the Image2ID folder. Inside the whiteboxattack directory, there is a file named train_gan.py, which the README suggests is intended for training a model; however, the script does not seem to serve this purpose, leading to confusion. Additionally, I encountered several issues while attempting to run the code, including [briefly mention specific errors or problems]. I believe it would be beneficial to update the README to accurately reflect the functionality of the train_gan.py script and address the issues present in the code for improved usability and clarity.

**Comment by ShimingWang98** [comment]
Fixed in commit [e97deba]. Thanks for noticing.

**Comment by ShimingWang98** [comment]
@umesh-21 Fixed in commit [e97deba]. Thanks for noticing.

**Comment by umesh-21** [comment]
Still, there is a problem reproducing or running your code. Please update the original one.
